source/SaLyrics.WebUI/Models/LyricsViewModel.cs
using SaLyrics.Entities;

namespace SaLyrics.WebUI.Models {
    public class LyricsViewModel {

        public Lyrics Lyrics { get; set; }

        public string ArtistSearchText { get; set; }
    }
}

source/SaLyrics.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SaLyrics.WebUI.Controllers {
    public class HomeController : Controller {
        public ActionResult Index() {
            ViewBag.Message = "Welcome to ASP.NET MVC!";

            return View();
        }

        public ActionResult About() {
            return View();
        }
    }
}

source/SaLyrics.WebUI/Controllers/LyricsController.cs
using System.Web.Mvc;
using SaLyrics.Entities;

namespace SaLyrics.WebUI.Controllers {
    public class LyricsController : Controller {

        [HttpGet]
        public ActionResult Index() {
            Models.LyricsViewModel DFD = new Models.LyricsViewModel {
                Lyrics = new Lyrics()
            };
            

            return View(DFD);
        }

        [HttpPost]
        public ActionResult Index(SaLyrics.WebUI.Models.LyricsViewModel viewModel){

            TryValidateModel(viewModel);

            return View(viewModel);
        }

    }
}

source/SaLyrics.WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}

<h2>About</h2>
<p>
     Put content here.
</p>

source/SaLyrics.WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>@ViewBag.Message</h2>
<p>
    To learn more about ASP.NET MVC visit <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
</p>

source/SaLyrics.WebUI/Views/Lyrics/Index.cshtml
@model SaLyrics.WebUI.Models.LyricsViewModel

@{
    ViewBag.Title = "Index"; 
}

<div style="text-align:center">
@foreach (string item in Model.Lyrics.ZeroToZArtistPrefix)
	{
  <b >
		    @Html.ActionLink(item.ToString().ToUpper(), "Index", "Lyrics",null, new  { id=item})
        </b>
	}
  </div>
  <div style="text-align:center">
  @Html.TextBoxFor(x => x.ArtistSearchText)
     
     <input  type="button" value="Search"/>

  </div>





source/SaLyrics.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
</head>

<body>
    <div class="page">

        <div id="header">
            <div id="title">
                <h1>AZSALyrics get th real message</h1>
            </div>

            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>

            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Lyrics","Index","Lyrics")</li>
                </ul>

            </div>
        </div>

        <div id="main">
            @RenderBody()
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

source/SaLyrics.WebUI/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <b>@Context.User.Identity.Name</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}